### ISSUE TITLE
Windows 7 64 bit, Won't parse replays

### ISSUE THREAD

**Issue by haurang** [Zednosius/RocketLeagueReplayHandler#1]
If run via .py file the command line says that fetching etc. is complete but nothing seems to be happening. 

Running Windows 7 64 bit, intel i5, some old AMD card. 

Rocket League installed on a secondary disk.

**Comment by Zednosius** [comment]
Could you check if the replay directory is in its default location?
The default location is C:\Users<username>\Documents\My Games\Rocket
League\TAGame\Demos . I suspect it might have changed when Rocket League is
installed to a secondary disk.
If that's the case I'll make sure to add a way to specify the replay
directory.

/Zed

2015-12-03 22:17 GMT+01:00 haurang notifications@github.com:

**Comment by Zednosius** [comment]
I think I tracked it down partially to me using the wrong functions to create folders. I had in the past used a recursive one and forgot to change it. So when it should have thrown an error it instead just silently made all the folders required and made it look like it worked.

I've included a fix for this in the 1.1.1 release which is on the master branch, now if the replays are not in their usual location you'll get a dialog that asks for their location. I believe this should resolve the issue, so if you could test that out it'd be great. (You'll probably have to delete the empty folders "...\Rocket
League\TAGame\Demos" for it to work, make sure they really are empty first though)

**Comment by haurang** [comment]
Ok, so I've found the problem. I tried the new version and it didn't even create any folders, but I remembered I changed the Documents folder to another disk (through some Windows dialogue) some time back and that seems to be what is causing the trouble. If I manually copy the whole Rocket League folder from My Games over to my system disk everything works perfectly! So unless you figure out how to fix that somehow I can just manually copy my replays over, not a big deal.

**Comment by Zednosius** [comment]
I pushed an update to the master branch. If you make a file called 'replay.path' in the same folder as RocketLeagueReplayHandler and then copy the path you have to your demo directory then it should work i think. You shouldn't have to copy everytime :)

**Comment by haurang** [comment]
Yup, that works perfectly fine. Thank you so much for this by the way, now I have no excuses to not learn some editing stuff! This program is something they really should integrate into the game.

**Comment by Zednosius** [comment]
Excellent! I'll mark this as solved then :) :+1:
